version: 3

project:
  id: mocklocation
  name: MockLocation

paths:
  exclude:
    - build/
    - .gradle/
    - app/build/
    - "**/*.apk"
    - "**/*.jar"

analyze:
  modules:
    - name: app-runtime
      type: gradle
      path: app
      options:
        gradle:
          configurations:
            - releaseRuntimeClasspath
